### PR TITLE
Minor amendment to code/03...01...08....Rmd

### PR DESCRIPTION
**Pull request by terrymclaughlin**
Minor amendment to code/03_Analysis_01_Charts_and_Tables_08_Number_of_De
aths.Rmd to remove extraneous "Open" from header in section 04 - Open
NRS Deaths dataset.

### CODE REVIEW

**Comment by terrymclaughlin** [comment]
Thanks for approving my last pull request and for identifying the extraneous "Open" in the header.  I've amended the file to remove this and would be grateful if you could merge this into the develop branch.

Thanks again,

Terry

**Comment by dianam21** [comment]
No problem at all! Thank you.

**Comment by terrymclaughlin** [comment]
Hi Diana,

I merged this change into the develop branch as it's so minor, but I need it in place so I push my next set of changes to GitHub.

Terry

**Comment by dianam21** [comment]
Thank you for letting me know, Terry!

**Pull request merged**
